---
- name: Ensure krb5 realms are defined
  ini_file:
    path: /etc/krb5.conf
    section: domain_realm
    option: "{{ item }}"
    value: "{{ ipaclient_domain|upper }}"
  with_items:
  - "{{ ipaclient_krb5_extra_domains }}"
  when: ipaclient_krb5_extra_domains|length > 0


- name: Ensure krb5 DNS lookups are configured
  ini_file:
    path: /etc/krb5.conf
    section: libdefaults
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
  - option: dns_lookup_realm
    value: "{{ ipaclient_krb5_dns_lookup_realm }}"
  - option: dns_lookup_kdc
    value: "{{ ipaclient_krb5_dns_lookup_kdc }}"
  - option: dns_canonicalize_hostname
    value: "{{ ipaclient_krb5_dns_canonicalize_hostname }}"
